# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-08 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0014_auto_20170908_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='empleado',
        ),
        migrations.AlterField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='almacen.Proveedor'),
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
    ]
